apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dtome-pe/dtome-pe_iot
    targetRevision: HEAD
    path: confs/manifests  # This should match your repo folder with YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true