apiVersion: v1
kind: Pod
metadata:
  name: playground-pod
  namespace: dev
spec:
  tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: playground
    image: wil42/playground:v2
    ports:
    - containerPort: 80